<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class JarenalDocumentsBlockHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="int") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['nonce']) || (! empty($this->class->fieldMappings['nonce']['nullable']) && array_key_exists('nonce', $data))) {
            $value = $data['nonce'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['nonce']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['nonce']->setValue($document, $return);
            $hydratedData['nonce'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['timestamp']) || (! empty($this->class->fieldMappings['timestamp']['nullable']) && array_key_exists('timestamp', $data))) {
            $value = $data['timestamp'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['timestamp']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['timestamp']->setValue($document, $return);
            $hydratedData['timestamp'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['hash']) || (! empty($this->class->fieldMappings['hash']['nullable']) && array_key_exists('hash', $data))) {
            $value = $data['hash'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['hash']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['hash']->setValue($document, $return);
            $hydratedData['hash'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['previous_hash']) || (! empty($this->class->fieldMappings['previous_hash']['nullable']) && array_key_exists('previous_hash', $data))) {
            $value = $data['previous_hash'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['previous_hash']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['previous_hash']->setValue($document, $return);
            $hydratedData['previous_hash'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['transactions']) ? $data['transactions'] : null;
        $return = $this->dm->getConfiguration()->getPersistentCollectionFactory()->create($this->dm, $this->class->fieldMappings['transactions']);
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['transactions']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['transactions']->setValue($document, $return);
        $hydratedData['transactions'] = $return;
        return $hydratedData;
    }
}