<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class JarenalDocumentsTransactionHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['from']) || (! empty($this->class->fieldMappings['from']['nullable']) && array_key_exists('from', $data))) {
            $value = $data['from'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['from']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['from']->setValue($document, $return);
            $hydratedData['from'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['to']) || (! empty($this->class->fieldMappings['to']['nullable']) && array_key_exists('to', $data))) {
            $value = $data['to'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['to']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['to']->setValue($document, $return);
            $hydratedData['to'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['value']) || (! empty($this->class->fieldMappings['value']['nullable']) && array_key_exists('value', $data))) {
            $value = $data['value'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['value']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['value']->setValue($document, $return);
            $hydratedData['value'] = $return;
        }
        return $hydratedData;
    }
}